"""Definition of Done checker -- 30 checks mapped to SKILL.md section 9.

Two-tier validation design
--------------------------
The pipeline uses two complementary validation tiers:

**Tier 1 — Step 28 (BLOCKING GATE): QA Audit**
    ``qa_audit.py`` runs 17 structural checks (spec section 8a-8k) that
    verify the pipeline produced well-formed output: manifests exist, files
    are covered, citations parse, reports render, etc.  Failures **halt the
    pipeline** via ``BlockingGateError`` — no reports are generated if
    structural integrity is compromised.

**Tier 2 — Step 35 (NON-BLOCKING): Definition of Done**
    This module runs 30 substantive checks that evaluate *completeness and
    quality* of the analysis: every customer has all 4 agents' output, gaps
    are tracked, cross-references reconciled, Judge scores meet thresholds,
    etc.  These run during shutdown and produce ``dod_results.json``.
    Failures are logged and set the pipeline exit status (via
    ``CRITICAL_DOD_CHECKS``) but do **not** halt the pipeline — the reports
    are already generated by this point.

This split is intentional: structural checks must block (broken output is
useless), while completeness checks inform the user of quality gaps without
preventing them from accessing the reports they've already paid for.

Groups
------
- Core Analysis (1-12)  -- ALWAYS required.
- Reporting (13-17)     -- ALWAYS required.
- Contract Dates (18)   -- Conditional on ``source_of_truth.customer_database``.
- Extraction (19)       -- ALWAYS required.
- Judge (20-23)         -- Conditional on ``judge.enabled``.
- Incremental (24-27)   -- Conditional on ``execution_mode == "incremental"``.
- Report Consistency (28-30) -- ALWAYS required.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

from dd_agents.models.audit import AuditCheck
from dd_agents.utils.constants import ALL_SPECIALIST_AGENTS

logger = logging.getLogger(__name__)


class DefinitionOfDoneChecker:
    """Run 30 DoD checks and return a list of AuditCheck results.

    Parameters
    ----------
    run_dir:
        Root of the current pipeline run.
    inventory_dir:
        Inventory directory.
    customer_safe_names:
        Expected customer safe names.
    deal_config:
        Parsed deal configuration dictionary.
    """

    # Check group boundaries
    CORE_ANALYSIS = range(1, 13)  # 1-12
    REPORTING = range(13, 18)  # 13-17
    CONTRACT_DATES = (18,)  # 18
    EXTRACTION = (19,)  # 19
    JUDGE = range(20, 24)  # 20-23
    INCREMENTAL = range(24, 28)  # 24-27
    REPORT_CONSISTENCY = range(28, 31)  # 28-30

    def __init__(
        self,
        run_dir: Path,
        inventory_dir: Path,
        customer_safe_names: list[str],
        deal_config: dict[str, Any] | None = None,
    ) -> None:
        self.run_dir = run_dir
        self.inventory_dir = inventory_dir
        self.customer_safe_names = customer_safe_names
        self.deal_config = deal_config or {}

    # ------------------------------------------------------------------ #
    # public API
    # ------------------------------------------------------------------ #

    def check_all(self) -> list[AuditCheck]:
        """Run all applicable DoD checks and return results."""
        results: list[AuditCheck] = []

        # Core Analysis (1-12) -- always required
        results.append(self.check_1_customer_outputs_complete())
        results.append(self.check_2_file_coverage_complete())
        results.append(self.check_3_agent_manifests_valid())
        results.append(self.check_4_governance_resolved())
        results.append(self.check_5_citations_valid())
        results.append(self.check_6_gaps_tracked())
        results.append(self.check_7_cross_customer_patterns())
        results.append(self.check_8_cross_reference_reconciliation())
        results.append(self.check_9_ghost_customers())
        results.append(self.check_10_reference_files_processed())
        results.append(self.check_11_audit_logs_exist())
        results.append(self.check_12_domain_coverage())
        results.append(self.check_12b_agent_coverage_in_merged())

        # Reporting (13-17) -- always required
        results.append(self.check_13_merge_dedup_complete())
        results.append(self.check_14_excel_sheets_populated())
        results.append(self.check_15_audit_json_valid())
        results.append(self.check_16_entity_resolution_log())
        results.append(self.check_17_numerical_manifest_valid())

        # Contract Dates (18) -- conditional
        results.append(self.check_18_contract_dates_reconciled())

        # Extraction (19) -- always required
        results.append(self.check_19_extraction_quality())

        # Judge (20-23) -- conditional on judge.enabled
        if self.deal_config.get("judge", {}).get("enabled", False):
            results.append(self.check_20_quality_scores_exist())
            results.append(self.check_21_p0_spot_checked())
            results.append(self.check_22_threshold_met())
            results.append(self.check_23_contradictions_resolved())

        # Incremental (24-27) -- conditional on execution_mode
        exec_mode = self.deal_config.get("execution", {}).get("execution_mode", "full")
        if exec_mode == "incremental":
            results.append(self.check_24_classification_exists())
            results.append(self.check_25_carried_forward_metadata())
            results.append(self.check_26_run_history_updated())
            results.append(self.check_27_prior_run_archived())

        # Report Consistency (28-30) -- always required
        results.append(self.check_28_schema_driven_generation())
        results.append(self.check_29_schema_validation_passed())
        results.append(self.check_30_report_diff())

        return results

    # ------------------------------------------------------------------ #
    # Core Analysis (1-12)
    # ------------------------------------------------------------------ #

    def check_1_customer_outputs_complete(self) -> AuditCheck:
        """Every customer has output from ALL 4 agents."""
        missing: list[str] = []
        for customer in self.customer_safe_names:
            for agent in ALL_SPECIALIST_AGENTS:
                path = self.run_dir / "findings" / agent / f"{customer}.json"
                if not path.exists():
                    missing.append(f"{customer}/{agent}")
        return AuditCheck(
            passed=len(missing) == 0,
            dod_checks=[1],
            details={"missing_outputs": missing[:50]},
        )

    def check_2_file_coverage_complete(self) -> AuditCheck:
        """All discovered files are covered by at least one agent."""
        files_txt = self.inventory_dir / "files.txt"
        if not files_txt.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[2],
                details={"total_files": 0, "error": "files.txt missing"},
            )
        raw = files_txt.read_text(encoding="utf-8").strip()
        all_files = [line.strip() for line in raw.splitlines() if line.strip()]
        total = len(all_files)
        if total == 0:
            return AuditCheck(
                passed=False,
                dod_checks=[2],
                details={"total_files": 0, "error": "files.txt is empty"},
            )
        # Check that every file is covered by at least one agent manifest.
        covered: set[str] = set()
        findings_dir = self.run_dir / "findings"
        for agent in ALL_SPECIALIST_AGENTS:
            manifest_path = findings_dir / agent / "coverage_manifest.json"
            if not manifest_path.exists():
                continue
            try:
                mdata = json.loads(manifest_path.read_text(encoding="utf-8"))
                # Support multiple manifest formats:
                #   - files_covered / covered: list[str] or list[dict]
                #   - files_read: list[dict] with path key (CoverageManifest model)
                #   - files_assigned: list[str]
                for key in ("files_covered", "covered", "files_read", "files_assigned"):
                    for f in mdata.get(key, []):
                        fname = f if isinstance(f, str) else f.get("file_path", f.get("path", ""))
                        if fname:
                            covered.add(Path(fname).name)
            except (json.JSONDecodeError, OSError):
                continue
        all_basenames = {Path(f).name for f in all_files}
        uncovered = all_basenames - covered
        return AuditCheck(
            passed=len(uncovered) == 0,
            dod_checks=[2],
            details={
                "total_files": total,
                "covered_files": len(covered & all_basenames),
                "uncovered_files": len(uncovered),
                "uncovered_sample": sorted(uncovered)[:20],
            },
        )

    def check_3_agent_manifests_valid(self) -> AuditCheck:
        """All 4 agent manifests exist with consistent counts."""
        missing: list[str] = []
        invalid: list[str] = []
        for agent in ALL_SPECIALIST_AGENTS:
            manifest_path = self.run_dir / "findings" / agent / "coverage_manifest.json"
            if not manifest_path.exists():
                missing.append(agent)
                continue
            try:
                mdata = json.loads(manifest_path.read_text(encoding="utf-8"))
                # Validate that manifest has meaningful content
                files_covered = mdata.get("files_covered", mdata.get("covered", []))
                customers_processed = mdata.get("customers_processed", mdata.get("customers", []))
                if not files_covered and not customers_processed:
                    invalid.append(f"{agent}: empty manifest (no files or customers)")
            except (json.JSONDecodeError, OSError):
                invalid.append(f"{agent}: unreadable manifest")
        return AuditCheck(
            passed=len(missing) == 0 and len(invalid) == 0,
            dod_checks=[3],
            details={
                "missing_manifests": missing,
                "invalid_manifests": invalid,
                "all_manifests_valid": len(missing) == 0 and len(invalid) == 0,
            },
        )

    def check_4_governance_resolved(self) -> AuditCheck:
        """Every customer has governance resolved for all files OR explicit gaps."""
        audit_path = self.run_dir / "audit.json"
        if audit_path.exists():
            try:
                data = json.loads(audit_path.read_text(encoding="utf-8"))
                checks = data.get("checks", {})
                gov_check = checks.get("governance_completeness", {})
                passed = gov_check.get("passed", False)
                return AuditCheck(
                    passed=passed,
                    dod_checks=[4],
                    details={"governance_check": "from_qa_audit", "qa_result": gov_check},
                )
            except (json.JSONDecodeError, OSError):
                pass
        return AuditCheck(
            passed=False,
            dod_checks=[4],
            details={"governance_check": "qa_audit_not_run_yet"},
        )

    def check_5_citations_valid(self) -> AuditCheck:
        """Every finding has a valid citation."""
        audit_path = self.run_dir / "audit.json"
        if audit_path.exists():
            try:
                data = json.loads(audit_path.read_text(encoding="utf-8"))
                checks = data.get("checks", {})
                cit_check = checks.get("citation_integrity", {})
                passed = cit_check.get("passed", False)
                return AuditCheck(
                    passed=passed,
                    dod_checks=[5],
                    details={"citation_check": "from_qa_audit", "qa_result": cit_check},
                )
            except (json.JSONDecodeError, OSError):
                pass
        return AuditCheck(
            passed=False,
            dod_checks=[5],
            details={"citation_check": "qa_audit_not_run_yet"},
        )

    def check_6_gaps_tracked(self) -> AuditCheck:
        """Every referenced-but-missing document is logged as a gap."""
        merged_dir = self.run_dir / "findings" / "merged"
        if not merged_dir.exists() or not any(merged_dir.glob("*.json")):
            return AuditCheck(
                passed=False,
                dod_checks=[6],
                details={"error": "merged findings directory missing or empty"},
            )
        # Verify that merged customer files contain a 'gaps' key (even if empty).
        # This proves the merge step ran gap tracking, not just finding merge.
        customers_checked = 0
        customers_with_gap_tracking = 0
        for jf in sorted(merged_dir.glob("*.json")):
            if jf.stem.startswith("_") or jf.stem == "coverage_manifest":
                continue
            try:
                data = json.loads(jf.read_text(encoding="utf-8"))
                customers_checked += 1
                # The merge step writes a "gaps" key for every customer —
                # its presence proves gap tracking ran for this customer.
                if "gaps" in data:
                    customers_with_gap_tracking += 1
            except (json.JSONDecodeError, OSError):
                continue
        passed = customers_checked > 0 and customers_with_gap_tracking == customers_checked
        return AuditCheck(
            passed=passed,
            dod_checks=[6],
            details={
                "customers_checked": customers_checked,
                "customers_with_gap_tracking": customers_with_gap_tracking,
            },
        )

    def check_7_cross_customer_patterns(self) -> AuditCheck:
        """Cross-customer pattern check has run."""
        audit_path = self.run_dir / "audit.json"
        if audit_path.exists():
            try:
                data = json.loads(audit_path.read_text(encoding="utf-8"))
                checks = data.get("checks", {})
                xref_check = checks.get("cross_reference_completeness", {})
                passed = xref_check.get("passed", False)
                return AuditCheck(
                    passed=passed,
                    dod_checks=[7],
                    details={"cross_customer_check": "from_qa_audit", "qa_result": xref_check},
                )
            except (json.JSONDecodeError, OSError):
                pass
        return AuditCheck(
            passed=False,
            dod_checks=[7],
            details={"cross_customer_check": "qa_audit_not_run_yet"},
        )

    def check_8_cross_reference_reconciliation(self) -> AuditCheck:
        """Completed for ALL customers with reference data."""
        audit_path = self.run_dir / "audit.json"
        if audit_path.exists():
            try:
                data = json.loads(audit_path.read_text(encoding="utf-8"))
                checks = data.get("checks", {})
                xref_check = checks.get("cross_reference_completeness", {})
                passed = xref_check.get("passed", False)
                return AuditCheck(
                    passed=passed,
                    dod_checks=[8],
                    details={"reconciliation_check": "from_qa_audit", "qa_result": xref_check},
                )
            except (json.JSONDecodeError, OSError):
                pass
        return AuditCheck(
            passed=False,
            dod_checks=[8],
            details={"reconciliation_check": "qa_audit_not_run_yet"},
        )

    def check_9_ghost_customers(self) -> AuditCheck:
        """All ghost customers logged as P0 gaps."""
        audit_path = self.run_dir / "audit.json"
        if audit_path.exists():
            try:
                data = json.loads(audit_path.read_text(encoding="utf-8"))
                checks = data.get("checks", {})
                gap_check = checks.get("gap_completeness", {})
                passed = gap_check.get("passed", False)
                return AuditCheck(
                    passed=passed,
                    dod_checks=[9],
                    details={"ghost_check": "from_qa_audit", "qa_result": gap_check},
                )
            except (json.JSONDecodeError, OSError):
                pass
        return AuditCheck(
            passed=False,
            dod_checks=[9],
            details={"ghost_check": "qa_audit_not_run_yet"},
        )

    def check_10_reference_files_processed(self) -> AuditCheck:
        """All reference files processed by at least one agent.

        First checks if the QA audit already verified this (preferred path).
        Falls back to checking reference_files.json in inventory.  When no
        reference files exist, the check passes vacuously.
        """
        # Prefer QA audit result when available (same pattern as checks 4-9, 12).
        audit_path = self.run_dir / "audit.json"
        if audit_path.exists():
            try:
                data = json.loads(audit_path.read_text(encoding="utf-8"))
                checks = data.get("checks", {})
                ref_check = checks.get("cross_reference_completeness", {})
                if ref_check:
                    return AuditCheck(
                        passed=ref_check.get("passed", False),
                        dod_checks=[10],
                        details={"reference_files_check": "from_qa_audit", "qa_result": ref_check},
                    )
            except (json.JSONDecodeError, OSError):
                pass
        # Fallback: verify reference_files.json exists
        ref_path = self.inventory_dir / "reference_files.json"
        if not ref_path.exists():
            # No reference files manifest — if no _reference/ dir exists either,
            # there simply are no reference files and the check passes.
            ref_dir = self.inventory_dir.parent / "_reference"
            if not ref_dir.exists():
                return AuditCheck(passed=True, dod_checks=[10], details={"total_reference_files": 0})
            return AuditCheck(
                passed=False,
                dod_checks=[10],
                details={"reference_files_json_exists": False},
            )
        try:
            raw = json.loads(ref_path.read_text(encoding="utf-8"))
            ref_files = raw if isinstance(raw, list) else raw.get("files", [])
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[10],
                details={"error": "reference_files.json is invalid"},
            )
        if not ref_files:
            return AuditCheck(passed=True, dod_checks=[10], details={"total_reference_files": 0})
        # Check that each ref file appears in at least one agent's output.
        ref_basenames = {
            Path(f if isinstance(f, str) else f.get("file_path", f.get("path", ""))).name for f in ref_files
        }
        unprocessed = set(ref_basenames)
        # Search per-agent directories for processed reference files.
        # Manifests may live at findings/{agent}/ or findings/agents/{agent}/.
        findings_dir = self.run_dir / "findings"
        for agent in ALL_SPECIALIST_AGENTS:
            for agent_dir in (findings_dir / agent, findings_dir / "agents" / agent):
                if not agent_dir.exists():
                    continue
                manifest = agent_dir / "reference_files_processed.json"
                if manifest.exists():
                    try:
                        processed = json.loads(manifest.read_text(encoding="utf-8"))
                        processed_names = {Path(p).name for p in (processed if isinstance(processed, list) else [])}
                        unprocessed -= processed_names
                    except (json.JSONDecodeError, OSError):
                        continue
        return AuditCheck(
            passed=len(unprocessed) == 0,
            dod_checks=[10],
            details={
                "total_reference_files": len(ref_basenames),
                "unprocessed_count": len(unprocessed),
            },
        )

    def check_11_audit_logs_exist(self) -> AuditCheck:
        """All 4 specialist audit logs exist.

        When audit log directories do not exist (common with SDK-based agents
        that don't write traditional audit logs), fall back to checking whether
        the QA audit completed successfully — a passing audit.json proves the
        pipeline ran to completion with auditable output.
        """
        required = [*ALL_SPECIALIST_AGENTS]
        missing = []
        for agent in required:
            log_path = self.run_dir / "audit" / agent / "audit_log.jsonl"
            if not log_path.exists() or log_path.stat().st_size == 0:
                missing.append(agent)
        if not missing:
            return AuditCheck(passed=True, dod_checks=[11], details={"missing_audit_logs": []})
        # Fallback: if the QA audit passed, the pipeline completed with auditable
        # output even though per-agent audit logs are absent.
        audit_path = self.run_dir / "audit.json"
        if audit_path.exists():
            try:
                data = json.loads(audit_path.read_text(encoding="utf-8"))
                if data.get("audit_passed", False):
                    return AuditCheck(
                        passed=True,
                        dod_checks=[11],
                        details={
                            "missing_audit_logs": missing,
                            "fallback": "qa_audit_passed",
                            "note": "Per-agent audit logs absent but QA audit passed",
                        },
                    )
            except (json.JSONDecodeError, OSError):
                pass
        return AuditCheck(
            passed=False,
            dod_checks=[11],
            details={"missing_audit_logs": missing},
        )

    def check_12_domain_coverage(self) -> AuditCheck:
        """Every enabled analysis domain has findings OR clean-result per customer."""
        audit_path = self.run_dir / "audit.json"
        if audit_path.exists():
            try:
                data = json.loads(audit_path.read_text(encoding="utf-8"))
                checks = data.get("checks", {})
                dom_check = checks.get("domain_coverage", {})
                passed = dom_check.get("passed", False)
                return AuditCheck(
                    passed=passed,
                    dod_checks=[12],
                    details={"domain_coverage_check": "from_qa_audit", "qa_result": dom_check},
                )
            except (json.JSONDecodeError, OSError):
                pass
        return AuditCheck(
            passed=False,
            dod_checks=[12],
            details={"domain_coverage_check": "qa_audit_not_run_yet"},
        )

    def check_12b_agent_coverage_in_merged(self) -> AuditCheck:
        """Every customer in merged output has findings or gaps from all *assigned* agents."""
        merged_dir = self.run_dir / "findings" / "merged"
        if not merged_dir.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[12],
                details={"failures": ["Merged findings directory does not exist"]},
                rule="Check 12b: merged output covers all assigned agents per customer.",
            )

        # Load per-customer agent assignments from metadata if available.
        # Falls back to expecting all 4 agents when metadata is absent.
        customer_assignments: dict[str, list[str]] = {}
        metadata_path = self.run_dir / "metadata.json"
        try:
            meta = json.loads(metadata_path.read_text(encoding="utf-8"))
            customer_assignments = meta.get("customer_assignments", {})
        except (ValueError, OSError):
            pass

        default_agents = set(ALL_SPECIALIST_AGENTS)
        missing_coverage: list[str] = []

        for jf in sorted(merged_dir.glob("*.json")):
            try:
                data = json.loads(jf.read_text(encoding="utf-8"))
            except (ValueError, OSError):
                continue
            # Use the actual assignment for this customer, or all 4 as fallback
            expected_agents = set(customer_assignments.get(jf.stem, default_agents))
            actual_agents: set[str] = set()
            for f in data.get("findings", []):
                agent = f.get("agent", "")
                if agent:
                    actual_agents.add(agent)
            for g in data.get("gaps", []):
                agent = g.get("agent", "")
                if agent:
                    actual_agents.add(agent)
            missing = expected_agents - actual_agents
            if missing:
                missing_coverage.append(f"{jf.stem}: missing {sorted(missing)}")

        return AuditCheck(
            passed=len(missing_coverage) == 0,
            dod_checks=[12],
            details={
                "total_customers": len(list(merged_dir.glob("*.json"))),
                "customers_missing_agents": len(missing_coverage),
                "details": missing_coverage[:20],  # Cap at 20 to avoid huge output
            },
            rule="Check 12b: merged output covers all assigned agents per customer.",
        )

    # ------------------------------------------------------------------ #
    # Reporting (13-17)
    # ------------------------------------------------------------------ #

    def check_13_merge_dedup_complete(self) -> AuditCheck:
        """Merge step deduplicated findings from all 4 agents per customer."""
        merged_dir = self.run_dir / "findings" / "merged"
        if not merged_dir.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[13],
                details={"merged_count": 0, "expected_count": len(self.customer_safe_names)},
            )
        expected = set(self.customer_safe_names)
        matched = [f for f in merged_dir.glob("*.json") if f.stem in expected]
        count = len(matched)
        if count < len(self.customer_safe_names):
            return AuditCheck(
                passed=False,
                dod_checks=[13],
                details={
                    "merged_count": count,
                    "expected_count": len(self.customer_safe_names),
                    "missing": sorted(expected - {f.stem for f in matched})[:20],
                },
            )
        # Verify each merged file actually contains findings from multiple agents
        # (proving dedup ran, not just a copy).
        multi_agent_count = 0
        for jf in matched:
            try:
                data = json.loads(jf.read_text(encoding="utf-8"))
                agents_seen = {f.get("agent", "") for f in data.get("findings", [])}
                agents_seen.discard("")
                if len(agents_seen) >= 2:
                    multi_agent_count += 1
            except (json.JSONDecodeError, OSError):
                continue
        return AuditCheck(
            passed=True,
            dod_checks=[13],
            details={
                "merged_count": count,
                "expected_count": len(self.customer_safe_names),
                "customers_with_multi_agent_findings": multi_agent_count,
            },
        )

    def check_14_excel_sheets_populated(self) -> AuditCheck:
        """Excel report exists with populated sheets."""
        report_dir = self.run_dir / "report"
        xlsx_files = list(report_dir.glob("*.xlsx")) if report_dir.exists() else []
        if not xlsx_files:
            return AuditCheck(
                passed=False,
                dod_checks=[14],
                details={"error": "No .xlsx files found in report/"},
            )
        # Validate the first xlsx file has sheets with data.
        xlsx_path = xlsx_files[0]
        try:
            from openpyxl import load_workbook

            wb = load_workbook(xlsx_path, read_only=True, data_only=True)
            sheet_names = wb.sheetnames
            populated_sheets: list[str] = []
            empty_sheets: list[str] = []
            for name in sheet_names:
                ws = wb[name]
                # A sheet is "populated" if it has more than just a header row.
                row_count = 0
                for _ in ws.iter_rows(min_row=1, max_row=3):
                    row_count += 1
                if row_count >= 2:
                    populated_sheets.append(name)
                else:
                    empty_sheets.append(name)
            wb.close()
            return AuditCheck(
                passed=len(populated_sheets) >= 1 and len(sheet_names) >= 5,
                dod_checks=[14],
                details={
                    "total_sheets": len(sheet_names),
                    "populated_sheets": len(populated_sheets),
                    "empty_sheets": empty_sheets[:10],
                    "sheet_names": sheet_names,
                },
            )
        except Exception as exc:
            return AuditCheck(
                passed=False,
                dod_checks=[14],
                details={"error": f"Failed to read xlsx: {exc}", "xlsx_path": str(xlsx_path)},
            )

    def check_15_audit_json_valid(self) -> AuditCheck:
        """audit.json exists with audit_passed: true."""
        audit_path = self.run_dir / "audit.json"
        if not audit_path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[15],
                details={"error": "audit.json missing"},
            )
        try:
            data = json.loads(audit_path.read_text(encoding="utf-8"))
            return AuditCheck(
                passed=data.get("audit_passed", False),
                dod_checks=[15],
                details={"audit_passed": data.get("audit_passed", False)},
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[15],
                details={"error": "audit.json is invalid"},
            )

    def check_16_entity_resolution_log(self) -> AuditCheck:
        """Entity resolution log exists with zero unmatched that have aliases.

        Handles multiple output formats:
        - ``[]`` or ``{}`` — empty results (vacuously passes)
        - ``{"entries": [...]}`` — list of entity match entries
        - ``[{...}, ...]`` — direct list of entity match entries
        - ``{"unmatched": [...], "aliases_available": [...]}`` — QA audit format
        """
        log_path = self.run_dir / "entity_matches.json"
        if not log_path.exists():
            # Also check inside the inventory directory
            alt_path = self.inventory_dir / "entity_matches.json"
            if alt_path.exists():
                log_path = alt_path
            else:
                return AuditCheck(
                    passed=False,
                    dod_checks=[16],
                    details={"entity_matches_exists": False},
                )
        try:
            data = json.loads(log_path.read_text(encoding="utf-8"))
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[16],
                details={"error": "entity_matches.json is invalid"},
            )
        # Empty list or empty dict — no entities found, vacuously passes.
        if not data:
            return AuditCheck(
                passed=True,
                dod_checks=[16],
                details={"entity_matches_exists": True, "unmatched_with_aliases": 0, "note": "empty_result"},
            )
        # Count unmatched entities that have aliases available.
        unmatched_with_aliases = 0
        # Support both list format and dict-with-entries format
        entries = data if isinstance(data, list) else data.get("entries", data.get("unmatched", []))
        for entry in entries:
            if not isinstance(entry, dict):
                continue
            if not entry.get("matched", True) and (
                entry.get("aliases") or entry.get("aliases_available") or entry.get("alias_count", 0) > 0
            ):
                unmatched_with_aliases += 1
        return AuditCheck(
            passed=unmatched_with_aliases == 0,
            dod_checks=[16],
            details={
                "entity_matches_exists": True,
                "unmatched_with_aliases": unmatched_with_aliases,
                "total_entries": len(entries) if isinstance(entries, list) else 0,
            },
        )

    def check_17_numerical_manifest_valid(self) -> AuditCheck:
        """Numerical manifest exists with all audit layers validated."""
        manifest_path = self.run_dir / "numerical_manifest.json"
        if not manifest_path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[17],
                details={"error": "numerical_manifest.json missing"},
            )
        try:
            data = json.loads(manifest_path.read_text(encoding="utf-8"))
            numbers = data.get("numbers", [])
            entry_count = len(numbers)
            if entry_count < 10:
                return AuditCheck(
                    passed=False,
                    dod_checks=[17],
                    details={"entry_count": entry_count, "error": "fewer than 10 numerical entries"},
                )
            # Validate that entries have required fields (source, value, layer/derivation).
            valid_entries = 0
            missing_fields: list[str] = []
            for i, entry in enumerate(numbers[:50]):  # Sample first 50
                if not isinstance(entry, dict):
                    continue
                has_source = bool(entry.get("source") or entry.get("source_path") or entry.get("source_file"))
                has_value = entry.get("value") is not None or entry.get("original") is not None
                has_layer = bool(entry.get("layer") or entry.get("audit_layer") or entry.get("derivation"))
                if has_source and has_value:
                    valid_entries += 1
                elif i < 5:  # Report first 5 issues
                    missing_fields.append(f"entry[{i}]: source={has_source} value={has_value} layer={has_layer}")
            # Check that audit layers are represented
            layers_seen = {
                str(e.get("layer", e.get("audit_layer", e.get("derivation", ""))))
                for e in numbers
                if isinstance(e, dict)
            }
            layers_seen.discard("")
            return AuditCheck(
                passed=valid_entries >= 10 and len(layers_seen) >= 1,
                dod_checks=[17],
                details={
                    "entry_count": entry_count,
                    "valid_entries_sampled": valid_entries,
                    "layers_represented": sorted(layers_seen),
                    "missing_field_samples": missing_fields[:5],
                },
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[17],
                details={"error": "numerical_manifest.json is invalid"},
            )

    # ------------------------------------------------------------------ #
    # Contract Dates (18)
    # ------------------------------------------------------------------ #

    def check_18_contract_dates_reconciled(self) -> AuditCheck:
        """If customer_database exists: contract date reconciliation completed."""
        has_db = bool(self.deal_config.get("source_of_truth", {}).get("customer_database"))
        if not has_db:
            return AuditCheck(
                passed=True,
                dod_checks=[18],
                details={"applicable": False},
                rule="Not applicable -- no source_of_truth.customer_database.",
            )
        recon_path = self.run_dir / "contract_date_reconciliation.json"
        return AuditCheck(
            passed=recon_path.exists(),
            dod_checks=[18],
            details={
                "applicable": True,
                "reconciliation_file_exists": recon_path.exists(),
            },
        )

    # ------------------------------------------------------------------ #
    # Extraction (19)
    # ------------------------------------------------------------------ #

    def check_19_extraction_quality(self) -> AuditCheck:
        """Extraction quality log exists and covers extracted files."""
        eq_path = self.inventory_dir / "extraction_quality.json"
        if not eq_path.exists():
            alt_path = self.inventory_dir.parent / "index" / "text" / "extraction_quality.json"
            if alt_path.exists():
                eq_path = alt_path
        if not eq_path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[19],
                details={"error": "extraction_quality.json not found"},
            )
        try:
            data = json.loads(eq_path.read_text(encoding="utf-8"))
            # Support multiple formats:
            #   - list[dict]: direct list of entries
            #   - {"files": [...]} or {"entries": [...]}: wrapped list
            #   - dict[filepath -> entry_dict]: keyed by filepath (ExtractionQualityTracker format)
            entries: list[Any]
            if isinstance(data, list):
                entries = data
            elif isinstance(data, dict) and ("files" in data or "entries" in data):
                entries = data.get("files", data.get("entries", []))  # type: ignore[assignment]
            elif isinstance(data, dict):
                # dict keyed by filepath → entry_dict (ExtractionQualityTracker.save format)
                entries = list(data.values())
            else:
                entries = []
            if not entries:
                return AuditCheck(
                    passed=False,
                    dod_checks=[19],
                    details={"error": "extraction_quality.json has no entries", "path": str(eq_path)},
                )
            # Validate entries have quality metrics
            with_confidence = sum(
                1
                for e in entries
                if isinstance(e, dict) and (e.get("confidence") is not None or e.get("quality_score") is not None)
            )
            return AuditCheck(
                passed=len(entries) > 0,
                dod_checks=[19],
                details={
                    "total_entries": len(entries),
                    "entries_with_quality_score": with_confidence,
                    "path": str(eq_path),
                },
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[19],
                details={"error": "extraction_quality.json is invalid", "path": str(eq_path)},
            )

    # ------------------------------------------------------------------ #
    # Judge (20-23) -- conditional
    # ------------------------------------------------------------------ #

    def check_20_quality_scores_exist(self) -> AuditCheck:
        """quality_scores.json exists with valid scores for all 4 agents."""
        path = self.run_dir / "judge" / "quality_scores.json"
        if not path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[20],
                details={"error": "quality_scores.json missing"},
            )
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            agents_scored = set(data.get("agent_scores", {}).keys())
            all_scored = agents_scored >= set(ALL_SPECIALIST_AGENTS)
            return AuditCheck(
                passed=all_scored,
                dod_checks=[20],
                details={
                    "agents_scored": sorted(agents_scored),
                    "all_agents_scored": all_scored,
                },
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[20],
                details={"error": "quality_scores.json is invalid"},
            )

    def check_21_p0_spot_checked(self) -> AuditCheck:
        """All P0 findings spot-checked by Judge (100% sampling)."""
        path = self.run_dir / "judge" / "quality_scores.json"
        if not path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[21],
                details={"error": "quality_scores.json missing"},
            )
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            spot_checks = data.get("spot_checks", [])
            p0_checks = [sc for sc in spot_checks if sc.get("severity") == "P0"]
            # Pass if there are P0 spot checks OR if there are no P0 findings at all
            has_p0_findings = any(sc.get("severity") == "P0" for sc in data.get("spot_checks", [])) or any(
                f.get("severity") == "P0"
                for scores in data.get("agent_scores", {}).values()
                for f in (scores if isinstance(scores, list) else [])
            )
            # If no P0 findings exist in the data, the check passes
            # If P0 findings exist, we need spot checks for them
            passed = len(p0_checks) > 0 or not has_p0_findings
            return AuditCheck(
                passed=passed,
                dod_checks=[21],
                details={"p0_spot_checks": len(p0_checks), "has_p0_findings": has_p0_findings},
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[21],
                details={"error": "quality_scores.json is invalid"},
            )

    def check_22_threshold_met(self) -> AuditCheck:
        """All agents >= threshold OR quality caveats attached."""
        path = self.run_dir / "judge" / "quality_scores.json"
        if not path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[22],
                details={"error": "quality_scores.json missing"},
            )
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            threshold = self.deal_config.get("judge", {}).get("threshold", 70)
            below = []
            for agent, scores in data.get("agent_scores", {}).items():
                score = scores.get("score", scores.get("overall", 0))
                if score < threshold:
                    below.append(agent)
            return AuditCheck(
                passed=len(below) == 0,
                dod_checks=[22],
                details={
                    "threshold": threshold,
                    "below_threshold": below,
                },
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[22],
                details={"error": "quality_scores.json is invalid"},
            )

    def check_23_contradictions_resolved(self) -> AuditCheck:
        """All contradictions resolved -- zero unresolved."""
        path = self.run_dir / "judge" / "quality_scores.json"
        if not path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[23],
                details={"error": "quality_scores.json missing"},
            )
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            contradictions = data.get("contradictions", [])
            unresolved = [c for c in contradictions if not c.get("resolved", True)]
            return AuditCheck(
                passed=len(unresolved) == 0,
                dod_checks=[23],
                details={"unresolved_contradictions": len(unresolved)},
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[23],
                details={"error": "quality_scores.json is invalid"},
            )

    # ------------------------------------------------------------------ #
    # Incremental (24-27) -- conditional
    # ------------------------------------------------------------------ #

    def check_24_classification_exists(self) -> AuditCheck:
        """classification.json exists with valid status for every customer."""
        path = self.run_dir / "classification.json"
        if not path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[24],
                details={"error": "classification.json missing"},
            )
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            classifications = data if isinstance(data, dict) else {}
            # Each customer should have a classification status
            classified = {k: v for k, v in classifications.items() if isinstance(v, dict) and v.get("status")}
            expected = set(self.customer_safe_names)
            missing = expected - set(classified.keys())
            return AuditCheck(
                passed=len(missing) == 0 and len(classified) > 0,
                dod_checks=[24],
                details={
                    "classified_customers": len(classified),
                    "expected_customers": len(expected),
                    "missing_classifications": sorted(missing)[:20],
                },
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[24],
                details={"error": "classification.json is invalid"},
            )

    def check_25_carried_forward_metadata(self) -> AuditCheck:
        """Every carried-forward finding has _carried_forward and _original_run_id."""
        merged_dir = self.run_dir / "findings" / "merged"
        if not merged_dir.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[25],
                details={"error": "merged findings directory missing"},
            )
        missing_metadata: list[str] = []
        for jf in merged_dir.glob("*.json"):
            try:
                data = json.loads(jf.read_text(encoding="utf-8"))
            except (json.JSONDecodeError, OSError):
                continue
            for finding in data.get("findings", []):
                meta = finding.get("metadata", {})
                if meta.get("_carried_forward") and not meta.get("_original_run_id"):
                    missing_metadata.append(finding.get("id", "unknown"))
        return AuditCheck(
            passed=len(missing_metadata) == 0,
            dod_checks=[25],
            details={
                "findings_missing_original_run_id": missing_metadata[:50],
            },
        )

    def check_26_run_history_updated(self) -> AuditCheck:
        """run_history.json updated with current run."""
        history_path = Path(self.run_dir).parent.parent / "run_history.json"
        if not history_path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[26],
                details={"error": "run_history.json missing"},
            )
        try:
            data = json.loads(history_path.read_text(encoding="utf-8"))
            runs = data.get("runs", data) if isinstance(data, dict) else data
            if not isinstance(runs, list):
                runs = []
            # The current run_dir basename should appear in the history.
            run_name = self.run_dir.name
            run_ids = [str(r.get("run_id", r.get("id", ""))) if isinstance(r, dict) else str(r) for r in runs]
            current_found = any(run_name in rid for rid in run_ids)
            return AuditCheck(
                passed=current_found and len(runs) > 0,
                dod_checks=[26],
                details={
                    "total_runs": len(runs),
                    "current_run_recorded": current_found,
                    "current_run_name": run_name,
                },
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[26],
                details={"error": "run_history.json is invalid"},
            )

    def check_27_prior_run_archived(self) -> AuditCheck:
        """Prior run data archived intact."""
        prior_run_id = self.deal_config.get("execution", {}).get("prior_run_id", "")
        if not prior_run_id:
            return AuditCheck(
                passed=False,
                dod_checks=[27],
                details={"error": "No prior_run_id configured for incremental mode"},
            )
        # Check that the prior run's archive directory or metadata exists.
        archive_dir = self.run_dir.parent / prior_run_id
        metadata_path = archive_dir / "metadata.json"
        if not archive_dir.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[27],
                details={"error": f"Prior run directory {prior_run_id} not found"},
            )
        has_metadata = metadata_path.exists()
        # Verify the archive has key subdirectories (findings/, report/).
        has_findings = (archive_dir / "findings").exists()
        return AuditCheck(
            passed=has_metadata and has_findings,
            dod_checks=[27],
            details={
                "prior_run_id": prior_run_id,
                "archive_dir_exists": archive_dir.exists(),
                "metadata_exists": has_metadata,
                "findings_preserved": has_findings,
            },
        )

    # ------------------------------------------------------------------ #
    # Report Consistency (28-30)
    # ------------------------------------------------------------------ #

    def check_28_schema_driven_generation(self) -> AuditCheck:
        """report_schema.json is valid and contains sheet definitions."""
        schema_path = self.run_dir / "report_schema.json"
        if not schema_path.exists():
            return AuditCheck(
                passed=False,
                dod_checks=[28],
                details={"error": "report_schema.json missing"},
            )
        try:
            data = json.loads(schema_path.read_text(encoding="utf-8"))
            sheets = data.get("sheets", [])
            has_version = bool(data.get("schema_version"))
            return AuditCheck(
                passed=len(sheets) > 0 and has_version,
                dod_checks=[28],
                details={
                    "schema_version": data.get("schema_version", ""),
                    "sheet_count": len(sheets),
                    "sheet_names": [s.get("name", "") for s in sheets[:20]],
                },
            )
        except (json.JSONDecodeError, OSError):
            return AuditCheck(
                passed=False,
                dod_checks=[28],
                details={"error": "report_schema.json is invalid"},
            )

    def check_29_schema_validation_passed(self) -> AuditCheck:
        """Excel sheets match the schema: sheet names, column counts align."""
        schema_path = self.run_dir / "report_schema.json"
        report_dir = self.run_dir / "report"
        xlsx_files = list(report_dir.glob("*.xlsx")) if report_dir.exists() else []
        if not schema_path.exists() or not xlsx_files:
            return AuditCheck(
                passed=False,
                dod_checks=[29],
                details={
                    "error": "Missing report_schema.json or xlsx file",
                    "schema_exists": schema_path.exists(),
                    "xlsx_exists": len(xlsx_files) > 0,
                },
            )
        try:
            schema_data = json.loads(schema_path.read_text(encoding="utf-8"))
            expected_sheets = {s.get("name", "") for s in schema_data.get("sheets", []) if s.get("name")}

            from openpyxl import load_workbook

            wb = load_workbook(xlsx_files[0], read_only=True, data_only=True)
            actual_sheets = set(wb.sheetnames)
            wb.close()

            # Schema sheets that should be present (some may be conditional).
            # We check that at least 50% of schema sheets exist — conditional
            # sheets are excluded from the count.
            common = expected_sheets & actual_sheets
            missing = expected_sheets - actual_sheets
            extra = actual_sheets - expected_sheets
            coverage = len(common) / max(len(expected_sheets), 1)
            return AuditCheck(
                passed=coverage >= 0.5 and len(actual_sheets) >= 5,
                dod_checks=[29],
                details={
                    "expected_sheet_count": len(expected_sheets),
                    "actual_sheet_count": len(actual_sheets),
                    "matching_sheets": len(common),
                    "coverage_ratio": round(coverage, 2),
                    "missing_sheets": sorted(missing)[:10],
                    "extra_sheets": sorted(extra)[:10],
                },
            )
        except Exception as exc:
            return AuditCheck(
                passed=False,
                dod_checks=[29],
                details={"error": f"Schema validation failed: {exc}"},
            )

    def check_30_report_diff(self) -> AuditCheck:
        """If prior run exists: report_diff.json exists."""
        diff_path = self.run_dir / "report_diff.json"
        prior_run_id = self.deal_config.get("execution", {}).get("prior_run_id", "")
        if not prior_run_id:
            # No prior run -- check passes by default
            return AuditCheck(
                passed=True,
                dod_checks=[30],
                details={
                    "report_diff_exists": diff_path.exists(),
                    "prior_run_id": "",
                    "note": "No prior run configured; check passes by default",
                },
            )
        # Prior run is set -- report_diff.json must exist
        return AuditCheck(
            passed=diff_path.exists(),
            dod_checks=[30],
            details={
                "report_diff_exists": diff_path.exists(),
                "prior_run_id": prior_run_id,
            },
        )
